### ISSUE TITLE
Can't find VS2017 installation after installation and the required reboot has been done.

### ISSUE THREAD

**Issue by ruant** [dotnet/ProjFileTools#9]
### Installed product versions
- Visual Studio: Visual Studio 2017 RTM
  - Also have Visual Studio 2015 installed.
- This extension: 1.0.2

### Description
After installing VS2017 and rebooting, then trying to run the ProjectFileTools.vsix it fails.
Looks like it doesn't find the VS2017 installation.
After another reboot the installation works as expected.
Not sure if it's the installation tool or the VS2017 installation that should have prompted for one more reboot after first run of VS2017?
(As a side note, the same thing was happening to Microsoft.VisualStudio.RazorExtension.vsix)

```
The installation was unable to install the extension to all the selected products.  
For more information, click on the install log link at the bottom of the dialog.

This extension is not installable on any currently installed products.
```

```
09.03.2017 08:56:42 - Microsoft VSIX Installer
09.03.2017 08:56:42 - -------------------------------------------
09.03.2017 08:56:42 - Initializing Install...
09.03.2017 08:56:42 - Extension Details...
09.03.2017 08:56:42 - 	Identifier         : e22f3d7e-6b01-4ef8-b3cb-ea293a87b00e
09.03.2017 08:56:42 - 	Name               : Project File Tools
09.03.2017 08:56:42 - 	Author             : Microsoft
09.03.2017 08:56:42 - 	Version            : 1.0.2
09.03.2017 08:56:42 - 	Description        : Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.
09.03.2017 08:56:42 - 	Locale             : en-US
09.03.2017 08:56:42 - 	MoreInfoURL        : 
09.03.2017 08:56:42 - 	InstalledByMSI     : False
09.03.2017 08:56:42 - 	SupportedFrameworkVersionRange : [4.5,)
09.03.2017 08:56:42 - 
09.03.2017 08:56:42 - 	SignatureState     : ValidSignature
09.03.2017 08:56:42 - 	SignedBy           : Microsoft Corporation
09.03.2017 08:56:42 - 	Certificate Info   : 
09.03.2017 08:56:42 - 		-------------------------------------------------------
09.03.2017 08:56:42 - 		[Subject]       : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
09.03.2017 08:56:42 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
09.03.2017 08:56:42 - 		[Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF
09.03.2017 08:56:42 - 		[Not Before]    : 12.02.2016 02:12:29
09.03.2017 08:56:42 - 		[Not After]     : 12.05.2017 03:12:29
09.03.2017 08:56:42 - 		[Thumbprint]    : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C
09.03.2017 08:56:42 - 
09.03.2017 08:56:42 - 	Supported Products : 
09.03.2017 08:56:42 - 		Microsoft.VisualStudio.Community
09.03.2017 08:56:42 - 			Version : [15.0]
09.03.2017 08:56:42 - 
09.03.2017 08:56:42 - 	References         : 
09.03.2017 08:56:42 - 		-------------------------------------------------------
09.03.2017 08:56:42 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
09.03.2017 08:56:42 - 		Name         : Visual Studio MPF 15.0
09.03.2017 08:56:42 - 		Version      : [15.0]
09.03.2017 08:56:42 - 		MoreInfoURL  : 
09.03.2017 08:56:42 - 		Nested       : No
09.03.2017 08:56:42 - 
09.03.2017 08:56:42 - Signature Details...
09.03.2017 08:56:42 - 	Extension is signed with a valid signature.
09.03.2017 08:56:42 - 
09.03.2017 08:56:42 - Searching for applicable products...
09.03.2017 08:56:43 - Found installed product - Microsoft Visual Studio Community 2015
09.03.2017 08:56:43 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
09.03.2017 08:56:43 - Found installed product - Global Location
09.03.2017 08:56:43 - Found installed product - ssms
09.03.2017 08:56:43 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

### Steps to recreate
1. Installed VS2017 RTM
1. Installation wanted to reboot, so I did.
1. Run VS2017 for the first time.
1. Downloaded and run ProjectFileTools.vsix
1. Watch it fail

### Workaround
Do one more reboot, after first run of VS2017

### Current behavior
Installation fails due to not finding the VS2017 installation.

### Expected behavior
That it finds the installation since the installation is complete and the required reboot has been done.

**Comment by mlorbetske** [comment]
This seems like an issue with the VSIX installer, could you submit this issue via the Send Feedback button (near the top right) in VS so that this gets directed to the right folks please?

**Comment by ruant** [comment]
I did.
But I think i "found" the error. It's the entire VS installation (computer went to sleep during the first installation try, and i did a repair afterward)

I created a new VM, and installed it again, without the computer going to sleep 👍 , and now it works as expected.

Sorry for not mentioning it earlier on this issue.

**Comment by weitzhandler** [comment]
I actually tried installing VS anew and the issue still persists.

**Comment by weitzhandler** [comment]
@ruant can you please reference the issue you opened there over here?

**Comment by weitzhandler** [comment]
[This](https://github.com/dotnet/ProjFileTools/issues/61) fixed the issue.
